FROM node:22

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY pnpm-lock.yaml package.json ./
COPY pnpm-workspace.yaml ./
COPY apps/admin ./apps/admin

RUN corepack enable && corepack prepare pnpm@10.13.1 --activate
RUN pnpm config set injectWorkspacePackages true
RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/admin

EXPOSE 3001

CMD ["pnpm", "dev"]
