FROM node:22

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY pnpm-lock.yaml package.json ./
COPY pnpm-workspace.yaml ./
COPY apps/api ./apps/api

RUN corepack enable && corepack prepare pnpm@10.13.1 --activate
RUN pnpm config set injectWorkspacePackages true
RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/api

EXPOSE 3000

CMD ["pnpm", "start:dev"]
